auto: true
server: true
permalink: "/:year/:month/:day/:title"
baseurl: "http://dosviajerossinmemoria.com"
name: "Dos viajeros sin memoria"
description: "Aventuras de dos viajeros sin memoria"
markdown: rdiscount
exclude:
- .gitignore
- README.md
